results_dir: results/
summary_dir: results
costs_dir: data/ #TODO change to the equivalent of technology data
run: test

costs:
  lifetime: 25 #default lifetime
  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: 0.07
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   onwind: 500
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.

  lines:
    length_factor: 1.25 #to estimate offwind connection costs

sector:
  land_transport_fuel_cell_share: 0.15 # 1 means all FCEVs
    # 2020: 0
    # 2030: 0.05
    # 2040: 0.1
    # 2050: 0.15
  land_transport_electric_share: 0.85 # 1 means all EVs
    # 2020: 0
    # 2030: 0.25
    # 2040: 0.6
    # 2050: 0.85