# Write down config entries differing from config.default.yaml
#I used this config file for the creation of elec_s_5_ec_lcopt_3h.nc on 4 August
#The new file disables sector-specific data to provide lower to allow for transmission-level dispatch information
run: {}

countries: ["ZA"]

scenario:
  clusters: [5]
  opts: [3h]
  planning_horizons: [2030]

electricity:
  extendable_carriers:
    Generator: []        # Change from [solar, onwind, offwind-ac, offwind-dc, OCGT]
    StorageUnit: []      # Keep empty
    Store: []            # Change from [battery, H2]
    Link: []             # Keep empty

  estimate_renewable_capacities:
    stats: "irena"       # This will use actual installed capacities
    year: 2023
    p_nom_min: 1.0       # Use 100% of current capacity
    p_nom_max: 1.0       # Don't allow expansion beyond current

renewable:
  onwind:
    extendable: false    # Change from true
  offwind-ac:
    extendable: false    # Change from true
  offwind-dc:
    extendable: false    # Change from true
  solar:
    extendable: false    # Change from true
  hydro:
    extendable: false    # Change from true
  csp:
    extendable: false    # Change from true

sector:
  chp: false              # Add this - disable CHP constraints

solving:
  solver:
    name: highs
    options: highs-default

# Note that in the config file, The order of top-level sections doesn't matter, but indentation and structure absolutely do!