atlite:
  cutouts:
    cutout-2013-era5-tutorial:
      dx: 0.3
      dy: 0.3
      module: era5
  nprocesses: 4
augmented_line_connection:
  add_to_snakefile: false
  connectivity_upgrade: 2
  min_DC_length: 600
  min_expansion: 1
  new_line_type:
  - HVAC
base_network:
  min_voltage_rebase_voltage: 35000
  min_voltage_substation_offshore: 35000
build_osm_network:
  force_ac: false
  group_close_buses: true
  group_tolerance_buses: 5000
  overpassing_lines_tolerance: 1
  split_overpassing_lines: true
build_shape_options:
  contended_flag: set_by_country
  gadm_layer_id: 1
  gdp_method: standard
  nprocesses: 2
  out_logging: true
  update_file: false
  worldpop_method: standard
  year: 2020
clean_osm_data_options:
  add_line_endings: true
  generator_name_method: OSM
  names_by_shapes: true
  path_custom_cables: false
  path_custom_lines: false
  path_custom_substations: false
  tag_substation: transmission
  threshold_voltage: 35000
  use_custom_cables: OSM_only
  use_custom_lines: OSM_only
  use_custom_substations: OSM_only
cluster_options:
  aggregation_strategies:
    generators:
      committable: any
      efficiency: mean
      marginal_cost: mean
      p_min_pu: mean
      p_nom: sum
      p_nom_max: sum
      p_nom_min: sum
      ramp_limit_down: max
      ramp_limit_up: max
  alternative_clustering: false
  cluster_network:
    algorithm: kmeans
    exclude_carriers: []
    feature: solar+onwind-time
  distribute_cluster:
  - load
  out_logging: true
  simplify_network:
    algorithm: kmeans
    exclude_carriers: []
    feature: solar+onwind-time
    p_threshold_drop_isolated: 20
    p_threshold_merge_isolated: 300
    remove_stubs: true
    remove_stubs_across_borders: true
    s_threshold_fetch_isolated: 0.05
    to_substations: false
costs:
  USD2013_to_EUR2013: 0.7532
  emission_prices:
    co2: 0.0
  fill_values:
    CO2 intensity: 0
    FOM: 0
    VOM: 0
    discount rate: 0.07
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
  marginal_cost:
    H2: 0.0
    battery: 0.0
    battery inverter: 0.0
    electrolysis: 0.0
    fuel cell: 0.0
    hydro: 0.0
    offwind: 0.015
    onwind: 0.015
    solar: 0.01
  rooftop_share: 0.14
  version: v0.5.0
  year: 2030
countries:
- NG
- BJ
crs:
  area_crs: ESRI:54009
  distance_crs: EPSG:3857
  geo_crs: EPSG:4326
custom_rules: []
electricity:
  agg_p_nom_limits: data/agg_p_nom_minmax.csv
  automatic_emission: true
  automatic_emission_base_year: 1990
  base_voltage: 380.0
  co2base: 1487000000.0
  co2limit: 77500000.0
  conventional_carriers:
  - nuclear
  - oil
  - OCGT
  - CCGT
  - coal
  - lignite
  - geothermal
  - biomass
  custom_powerplants: false
  estimate_renewable_capacities:
    p_nom_max: false
    p_nom_min: 1
    stats: irena
    technology_mapping:
      Offshore:
      - offwind-ac
      - offwind-dc
      Onshore:
      - onwind
      PV:
      - solar
    year: 2020
  extendable_carriers:
    Generator:
    - solar
    - onwind
    - offwind-ac
    - offwind-dc
    - OCGT
    Link: []
    StorageUnit: []
    Store: []
  hvdc_as_lines: false
  max_hours:
    H2: 168
    battery: 6
  operational_reserve:
    activate: false
    contingency: 0
    epsilon_load: 0.02
    epsilon_vres: 0.02
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)
  renewable_carriers:
  - solar
  - onwind
  - offwind-ac
  - offwind-dc
  - hydro
  voltages:
  - 132.0
  - 220.0
  - 300.0
  - 380.0
  - 500.0
  - 750.0
enable:
  build_cutout: false
  build_natura_raster: true
  download_osm_data: true
  retrieve_cost_data: true
  retrieve_databundle: true
lines:
  ac_types:
    132.0: 243-AL1/39-ST1A 20.0
    220.0: Al/St 240/40 2-bundle 220.0
    300.0: Al/St 240/40 3-bundle 300.0
    380.0: Al/St 240/40 4-bundle 380.0
    500.0: Al/St 240/40 4-bundle 380.0
    750.0: Al/St 560/50 4-bundle 750.0
  dc_types:
    500.0: HVDC XLPE 1000
  length_factor: 1.25
  s_max_pu: 0.7
  s_nom_max: .inf
  under_construction: zero
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  under_construction: zero
load_options:
  prediction_year: 2030
  scale: 1
  ssp: ssp2-2.6
  weather_year: 2013
logging:
  format: '%(levelname)s:%(name)s:%(message)s'
  level: INFO
monte_carlo:
  options:
    add_to_snakefile: false
    samples: 9
    sampling_strategy: chaospy
    seed: 42
  uncertainties:
    generators_t.p_max_pu.loc[:, n.generators.carrier == "onwind"]:
      args:
      - 1.5
      type: lognormal
    generators_t.p_max_pu.loc[:, n.generators.carrier == "solar"]:
      args:
      - 0.5
      - 2
      type: beta
    loads_t.p_set:
      args:
      - 0
      - 1
      type: uniform
plotting:
  AC_carriers:
  - AC line
  - AC transformer
  conv_techs:
  - OCGT
  - CCGT
  - nuclear
  - coal
  - oil
  costs_max: 800
  costs_threshold: 1
  energy_max: 15000.0
  energy_min: -10000.0
  energy_threshold: 50.0
  link_carriers:
  - DC line
  - Converter AC-DC
  load_carriers:
  - AC load
  map:
    boundaries:
    - -10.2
    - 29
    - 35
    - 72
    figsize:
    - 7
    - 7
    p_nom:
      bus_size_factor: 50000.0
      linewidth_factor: 3000.0
  nice_names:
    CCGT: Combined-Cycle Gas
    H2: Hydrogen Storage
    OCGT: Open-Cycle Gas
    PHS: Pumped Hydro Storage
    battery: Battery Storage
    hydro: Reservoir & Dam
    lines: Transmission Lines
    offwind-ac: Offshore Wind (AC)
    offwind-dc: Offshore Wind (DC)
    onwind: Onshore Wind
    ror: Run of River
    solar: Solar
  storage_techs:
  - hydro+PHS
  - battery
  - H2
  tech_colors:
    AC line: '#70af1d'
    AC-AC: '#70af1d'
    CCGT: '#b20101'
    DC link: '#8a1caf'
    DC-DC: '#8a1caf'
    Electric load: '#f9d002'
    H2: '#ea048a'
    HVDC links: '#8a1caf'
    OCGT: '#d35050'
    PHS: '#08ad97'
    battery: '#b8ea04'
    biogas: '#23932d'
    biomass: '#0c6013'
    coal: '#707070'
    electricity: '#f9d002'
    gas: '#d35050'
    geothermal: '#ba91b1'
    hydro: '#08ad97'
    hydro reservoir: '#08ad97'
    hydro+PHS: '#08ad97'
    hydroelectricity: '#08ad97'
    hydrogen storage: '#ea048a'
    lignite: '#9e5a01'
    lines: '#70af1d'
    links: '#8a1caf'
    load: '#FF0000'
    natural gas: '#d35050'
    nuclear: '#ff9000'
    offshore wind: '#6895dd'
    offshore wind ac: '#6895dd'
    offshore wind dc: '#74c6f2'
    offwind: '#6895dd'
    offwind-ac: '#6895dd'
    offwind-dc: '#74c6f2'
    oil: '#262626'
    onshore wind: '#235ebc'
    onwind: '#235ebc'
    ror: '#4adbc8'
    run of river: '#4adbc8'
    solar: '#f9d002'
    solar PV: '#f9d002'
    solar thermal: '#ffef60'
    solid biomass: '#06540d'
    transmission lines: '#70af1d'
    waste: '#68896b'
  vre_techs:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror
renewable:
  hydro:
    PHS_max_hours: 6
    carriers:
    - ror
    - PHS
    - hydro
    clip_min_inflow: 1.0
    cutout: cutout-2013-era5-tutorial
    hydro_max_hours: energy_capacity_totals_by_country
    hydro_max_hours_default: 6.0
    hydrobasins_level: 4
    multiplier: 1.1
    normalization:
      method: hydro_capacities
      year: 2013
    resource:
      flowspeed: 1.0
      hydrobasins: data/hydrobasins/hybas_world.shp
      method: hydro
  offwind-ac:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 80
      - 200
    cutout: cutout-2013-era5-tutorial
    extendable: true
    max_depth: 50
    max_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  offwind-dc:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 80
      - 200
    cutout: cutout-2013-era5-tutorial
    extendable: true
    max_depth: 50
    min_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  onwind:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      distance: 1000
      distance_grid_codes:
      - 50
      grid_codes:
      - 20
      - 30
      - 40
      - 60
      - 100
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
    cutout: cutout-2013-era5-tutorial
    extendable: true
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: Vestas_V112_3MW
  solar:
    capacity_per_sqkm: 4.6
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 20
      - 30
      - 40
      - 50
      - 60
      - 90
      - 100
    correction_factor: 0.854337
    cutout: cutout-2013-era5-tutorial
    extendable: true
    natura: true
    potential: simple
    resource:
      method: pv
      orientation: latitude_optimal
      panel: CSi
retrieve_databundle:
  show_progress: false
run:
  name: ''
scenario:
  clusters:
  - 6
  ll:
  - copt
  opts:
  - Co2L-4H
  simpl:
  - ''
snapshots:
  end: 2013-03-7
  inclusive: left
  start: 2013-03-1
solving:
  options:
    clip_p_max_pu: 0.01
    formulation: kirchhoff
    load_shedding: true
    max_iterations: 6
    min_iterations: 4
    noisy_costs: true
    skip_iterations: true
    track_iterations: false
  solver:
    name: gurobi
summary_dir: results
transformers:
  s_nom: 2000.0
  type: ''
  x: 0.1
tutorial: true
version: 0.3.0
