# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# Changes with respect to the base configuration file specified in run->base_config
# default value is config.tutorial.yaml
run:
  name: NG  # Name of the configuration (arbitrary string value)
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
  base_config: config.tutorial.yaml  # base configuration file

countries:
- NG

scenario:
  clusters: [5]
