osm_clean_columns:
  substation:
    bus_id: object
    station_id: float
    voltage: float
    dc: bool
    symbol: object
    under_construction: bool
    tag_substation: str
    tag_area: str
    lon: float
    lat: float
    country: str
    geometry: object
  generator:
    id: object
    tags.power: object
    Type: object
    Country: str
    Area: object
    name: object
    tags.generator:type: object
    tags.generator:method: object
    tags.generator:source: object
    power_output_MW: object
    geometry: object
  line:
    line_id: object
    bus0: object
    bus1: object
    voltage: float
    circuits: float
    length: float
    underground: bool
    under_construction: bool
    tag_type: str
    tag_frequency: float
    dc: bool
    country: object
    geometry: object

continents:
  LA: NorthAmerica
  SA: SouthAmerica
  AS: Asia
  OC: Oceania
  AF: Africa
  EU: Europe

world_iso:
  Africa:
    DZ: algeria
    AO: angola
    BJ: benin
    BW: botswana
    BF: burkina-faso
    BI: burundi
    CM: cameroon
    CF: central-african-republic
    TD: chad
    CG: congo-brazzaville
    CD: congo-democratic-republic
    DJ: djibouti
    EG: egypt
    GQ: equatorial-guinea
    ER: eritrea
    ET: ethiopia
    GA: gabon
    GH: ghana
    GW: guinea-bissau
    GN: guinea
    CI: ivory-coast
    KE: kenya
    LS: lesotho
    LR: liberia
    LY: libya
    MG: madagascar
    MW: malawi
    ML: mali
    MR: mauritania
    MU: mauritius
    MA: morocco
    MZ: mozambique
    NA: namibia
    NE: niger
    NG: nigeria
    RW: rwanda
    SN: senegal
    GM: gambia
    SL: sierra-leone
    SO: somalia
    ZA: south-africa
    SS: south-sudan
    SD: sudan
    SZ: swaziland
    TZ: tanzania
    TG: togo
    TN: tunisia
    UG: uganda
    ZM: zambia
    ZW: zimbabwe
    EH: western-sahara
  Asia:
    AF: afghanistan
    AM: armenia
    AZ: azerbaijan
    BH: bahrain
    BD: bangladesh
    BT: bhutan
    KH: cambodia
    CN: china
    CY: cyprus
    GE: georgia
    IN: india
    ID: indonesia
    IR: iran
    IQ: iraq
    IL: israel
    JP: japan
    JO: jordan
    KZ: kazakhstan
    KP: north-korea
    KR: south-korea
    KW: kuwait
    KG: kyrgyzstan
    LA: lao-people's-democratic-republic
    LB: lebanon
    MY: malaysia
    BN: brunei
    MV: maldives
    MN: mongolia
    MM: myanmar
    NP: nepal
    OM: oman
    PK: pakistan
    PS: palestine
    PH: philippines
    QA: qatar
    RU: russian-federation
    SA: saudi-arabia
    SG: singapore
    LK: sri-lanka
    SY: syria
    TW: taiwan
    TJ: tajikistan
    TH: thailand
    TL: timor-leste
    TR: turkey
    TM: turkmenistan
    AE: united-arab-emirates
    UZ: uzbekistan
    VN: vietnam
    YE: yemen
  Oceania:
    AS: american-samoa
    AU: australia
    FJ: fiji
    KI: kiribati
   # "MP": "northern-mariana-islands",
# "PN": "pitcairn-islands",
# "AX": "aland-islands"
# "MS": "montserrat"
# "VI": "united-states-virgin-islands",
# "GI": "gibraltar",
# "IO": "british-indian-ocean-territory",
# "IM": "isle of man",  # Island
# "VG": "british-virgin-islands", # Islands
# "WS": "samoa"
# "KP": "north-korea"
# "SX": "sint-maarten"
# "TL": "east-timor"
# "VC": "saint-vincent-and-the-grenadines"
# "ST": "sao-tome-and-principe",
# "SC": "seychelles",
# "TC": "turks-and-caicos",
# "UM": "united-states-minor-outlying-islands", #Islands
# "WF": "wallis-and-futuna",  # Island
# "PN": "pitcairn-islands",  # Islands
# "CI": "cote-d-ivoire",
# "IR": "iran",
# "TF": "french-southern-territories",
# "SZ": "swaziland",
# "BV": "bouvet-island",
# "CG": "congo-brazzaville",
# "TK": "tokelau",
# "CX": "christmas-island",
# "PG": "papua-new-guinea",
# "VU": "vanuatu",
# "NU": "niue",
# "KI": "kiribati",
# "NF": "norfolk-island",
# "MP": "northern-mariana-islands",
# "FO": "faroe-islands",
# "CC": "cocos-islands",
# "TL": "east-timor",
# "XK": "kosovo",
# "TC": "turks-and-caicos-islands",
# "MF": "saint-martin",
# "SX": "sint-maarten",
# "BL": "saint-barthelemy",
# "CZ": "czech-republic",
# "SM": "san-marino",
# "VA": "vatican-city",
# "LA": "laos",
# "BQ": "bonaire-sint-eustatius-saba",
# "CW": "curacao",
# "PM": "saint-pierre-and-miquelon",
# "XS": "spratly-islands",
# "MF": "saint-martin",
# "TF": "french-southern-territories",
# "RE": "reunion",
# "CI": "cote-d-ivoire",
# "IR": "iran",
# "TF": "french-southern-territories",
# "SZ": "swaziland",
# "BV": "bouvet-island",
# "CG": "congo-brazzaville",
# "TK": "tokelau",
# "CX": "christmas-island",
# "PG": "papua-new-guinea",
# "VU": "vanuatu",
# "NU": "niue",
# "KI": "kiribati",
# "NF": "norfolk-island",
# "MP": "northern-mariana-islands",
# "FO": "faroe-islands",
# "CC": "cocos-islands",
# "TL": "east-timor",
# "XK": "kosovo",
# "TC": "turks-and-caicos-islands",
# "MF": "saint-martin",
# "SX": "sint-maarten",
# "BL": "saint-barthelemy",
# "CZ": "czech-republic",
# "SM": "san-marino",
# "VA": "vatican-city",
# "LA": "laos",
# "BQ": "bonaire-sint-eustatius-saba",
# "CW": "curacao",
# "PM": "saint-pierre-and-miquelon",
# "XS": "spratly-islands",
# "MF": "saint-martin",
# "TF": "french-southern-territories",
# "RE": "reunion",
# "CI": "cote-d-ivoire",
# "IR": "iran",
# "TF": "french-southern-territories",
# "SZ": "swaziland",
# "BV": "bouvet-island",
# "CG": "congo-brazzaville",
# "TK": "tokelau",
# "CX": "christmas-island",
# "PG": "papua-new-guinea",
# "VU": "vanuatu",
# "NU": "niue",
# "KI": "kiribati",
# "NF": "norfolk-island",
# "MP": "northern-mariana-islands",
# "FO": "faroe-islands",
# "CC": "cocos-islands",
# "TL": "east-timor",
# "XK": "kosovo",
# "TC": "turks-and-caicos-islands",
# "MF": "saint-martin",
# "SX": "sint-maarten",
# "BL": "saint-barthelemy",
# "CZ": "czech-republic",
# "SM": "san-marino",
# "VA": "vatican-city",
# "LA": "laos",
# "BQ": "bonaire-sint-eustatius-saba",
# "CW": "curacao",
# "PM": "saint-pierre-and-miquelon",
# "XS": "spratly-islands",
# "MF": "saint-martin",
# "TF": "french-southern-territories",
# "RE": "reunion",
# "CI": "cote-d-ivoire",
# "IR": "iran",
# "TF": "french-southern-territories",
# "SZ": "swaziland",
# "BV": "bouvet-island",
# "CG": "congo-brazzaville",
# "TK": "tokelau",
# "CX": "christmas-island",
# "PG": "papua-new-guinea",
# "VU": "vanuatu",
# "NU": "niue",
# "KI": "kiribati",
# "NF": "norfolk-island",
# "MP": "northern-mariana-islands",
# "FO": "faroe-islands",
# "CC": "cocos-islands",
# "TL": "east-timor",
# "XK": "kosovo",
# "TC": "turks-and-caicos-islands",
# "MF": "saint-martin",
# "SX": "sint-maarten",
# "BL": "saint-barthelemy
